package dev.civilizations.plugin;

import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.command.system.CommandContext;
import com.hypixel.hytale.server.core.command.system.basecommands.CommandBase;

/** Test-only bytecode marker; version B is generated by replacing its equal-length constant. */
final class CivReloadProbeCommand extends CommandBase {
    CivReloadProbeCommand() {
        super("civreloadmarker", "Displays the current runtime reload test marker.");
        requireNoPermission();
    }

    @Override
    protected void executeSync(CommandContext context) {
        context.sendMessage(Message.raw("CIV_RELOAD_MARKER_A"));
        System.out.println("CIV_RELOAD_MARKER_A");
    }
}
